

(rule
 (name data)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name data))
 (add
  (print data)
  (global-node next-color))
 (del
  (global-node rule ?this-rule)))

;; For extensions, see display-rules.lisp

(rule
 (name basic-display-data)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name basic-display-data))
 (add
  (print basic-display-data)
  ;; (fft color green)
  ;; (fft in-node-color springgreen)
  ;; (fft out-node-color darkturquoise)
  ;; (zero color seashell)
  (aup in-node-color deeppink)
  (aup out-node-color dodgerblue)
  ;; (aup edge-color springgreen)
  (aup color springgreen)
  (aup fontcolor springgreen)
  ;; (odd out-node-color palegreen)
  ;; (even out-node-color palevioletred)
  ;; (elem in-node-color  palevioletred)
  (elem out-node-color palevioletred)
  ;; (elem edge-color  darkturquoise)
  (elem color  darkturquoise)
  (tree-next color dodgerblue)
  (fft-comb two-input-op)
  (fft-comb color lightskyblue)

  (fft-hb two-input-op)
  ;; (fft-hb in-node-color deeppink)
  ;; (fft-hb out-node-color dodgerblue)
  (fft-hb color turquoise)
  (fft-hb shape ellipse)

  (fft-hb-delta two-input-op)
  (fft-hb-delta in-node-color springgreen)
  (fft-hb-delta color turquoise)

  ; * = both a gv node and gv edge attribute
  (color gv-attr)		; *
  (shape gv-attr)
  (label gv-attr)		; *
  (fontname gv-attr)	; *
  (fontsize gv-attr)	; *
  (fontcolor gv-attr)	; *
  (style gv-attr)		; *
  (width gv-attr)
  (height gv-attr)
  (fixedsize gv-attr)

  ;; (fwd-fe-rule color paleturquoise)

  (+ two-input-op))
 (del
  (global-node rule ?this-rule)))

(rule
 (name std-notes)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name std-notes))
 (add
  (print std-notes)
  (note footer "Copyright (c) 2026 Lawrence Stabile"))
 (del
  (global-node rule ?this-rule)))


(rule
 (name gen-inverse)
 (attach-to inverse)
 (root-var inverse)
 (pred
  (?a inverse ?i))
 (add
  (print gen-inverse ?a ?i)
  (?a rule
	  (rule
	   (name (add-inverse ?i))
	   (root-var ?a)
	   (pred
		(?x ?a ?y))
	   (add
		(print add-inverse ?a ?i ?x ?y)
		(?y ?i ?x))))))

(rule
 (name inverse-data)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name inverse-data))
 (add
  (print inverse-data)
  (member inverse is-member-of)
  (elem inverse is-elem-of))
 (del
  (?this-obj rule ?this-rule)))

;; This form of "is" and "is-not" replaces all other old ones. Much
;; better using the rest var and a "has" notation, allowing for
;; inheritance of arbitrary info without funny naming and so forth.

;; 10/22/24 pulled this back to get only rule attrs, better to trace rule-vars and so forth. 

(comment
(rule
 (name xis-gen)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name xis-gen)
  )
 (add
  (print xis-gen)
  ;; (xis exec)
  ;; (xis-not exec)
  (xis rule 
	   (rule
		(name xis)
		(pred
		 (?x xis ?y)
		 (?y has ?*r))
		(add
		 (print xis ?x ?y ?*r)
		 (?x ?*r))
		(del
		 (?x xis ?y))))
  (xis-not rule 
		   (rule
			(name xis-not)
			(pred
			 (?x xis-not ?y)
			 (?y has ?*r))
			(add
			 (print xis-not ?x ?y ?*r))
			(del
			 (?x xis ?y)
			 (?x xis-not ?y)
			 (?x ?*r))))
  )
 (del
  (?this-obj rule ?this-rule))
 )
)

(rule
 (name xis-gen)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r1)
  (?r1 name xis-gen)
  )
 (add
  (print xis-gen)
  (xis rule 
	   (rule
		(name xis)
		(pred
		 (?x xis ?y)
		 (?y has rule ?r))
		(add
		 (print xis ?x ?y ?r)
		 (?x rule ?r))
		(del
		 (?x xis ?y))))
  (xis-not rule 
		   (rule
			(name xis-not)
			(pred
			 (?x xis-not ?y)
			 (?y has rule ?r))
			(add
			 (print xis-not ?x ?y ?r))
			(del
			 (?x xis ?y)
			 (?x xis-not ?y)
			 (?x rule ?r))))
  )
 (del
  (?this-obj rule ?this-rule))
 )

;; Original color circle, expanded 8/22/26 

;; (comment
(rule
 (name color-circle-data)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name color-circle-data))
 (add
  (print color-circle-data)
  (navajowhite next-color moccasin)
  (moccasin next-color lemonchiffon)
  (lemonchiffon next-color seashell)
  (seashell next-color aliceblue)
  (aliceblue next-color lavender)
  (lavender next-color lavenderblush)
  (lavenderblush next-color mistyrose)
  (mistyrose next-color dodgerblue)
  (dodgerblue next-color deepskyblue)
  (deepskyblue next-color skyblue)
  (skyblue next-color lightskyblue)
  (lightskyblue next-color darkturquoise)
  (darkturquoise next-color mediumturquoise)
  (mediumturquoise next-color turquoise)
  (turquoise next-color cyan)
  (cyan next-color lightseagreen)
  (lightseagreen next-color palegreen)
  (palegreen next-color springgreen)
  (springgreen next-color darkkhaki)
  (darkkhaki next-color khaki)
  (khaki next-color yellow)
  (yellow next-color gold)
  (gold next-color salmon)
  (salmon next-color deeppink)
  (deeppink next-color pink)
  (pink next-color lightpink)
  (lightpink next-color palevioletred)
  (palevioletred next-color mediumvioletred)
  (mediumvioletred next-color violetred)
  (violetred next-color magenta)
  (magenta next-color violet)
  (violet next-color blueviolet)
  (blueviolet next-color purple)
  (purple next-color AntiqueWhite1)
  (AntiqueWhite1 next-color LemonChiffon1)
  (LemonChiffon1 next-color LemonChiffon2)
  (LemonChiffon2 next-color LemonChiffon3)
  (LemonChiffon3 next-color LavenderBlush1)
  (LavenderBlush1 next-color MistyRose2)
  (MistyRose2 next-color MistyRose3)
  (MistyRose3 next-color SlateBlue1)
  (SlateBlue1 next-color blue1)
  (blue1 next-color DodgerBlue3)
  (DodgerBlue3 next-color DeepSkyBlue3)
  (DeepSkyBlue3 next-color LightSkyBlue3)
  (LightSkyBlue3 next-color LightBlue1)
  (LightBlue1 next-color PaleTurquoise1)
  (PaleTurquoise1 next-color turquoise1)
  (turquoise1 next-color SpringGreen1)
  (SpringGreen1 next-color green2)
  (green2 next-color chartreuse2)
  (chartreuse2 next-color khaki1)
  (khaki1 next-color yellow1)
  (yellow1 next-color gold2)
  (gold2 next-color RosyBrown2)
  (RosyBrown2 next-color navajowhite))
 (del
  (global-node rule ?this-rule)))
;; )

(comment
(rule
 (name color-circle-data)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node rule ?r)
  (?r name color-circle-data))
 (add
  (red next-color orangered) 
  (orangered next-color darkorange) 
  (darkorange next-color orange) 
  (orange next-color gold) 
  (gold next-color yellow) 
  (yellow next-color chartreuse) 
  (chartreuse next-color lawngreen) 
  (lawngreen next-color green) 
  (green next-color springgreen) 
  (springgreen next-color mediumspringgreen) 
  (mediumspringgreen next-color cyan) 
  (cyan next-color deepskyblue) 
  (deepskyblue next-color blue) 
  (blue next-color mediumblue) 
  (mediumblue next-color darkviolet) 
  (darkviolet next-color darkmagenta) 
  (darkmagenta next-color magenta) 
  (magenta next-color darkred) 
  (darkred next-color brown) 
  (brown next-color firebrick) 
  (firebrick next-color indianred) 
  (indianred next-color lightcoral) 
  (lightcoral next-color salmon) 
  (salmon next-color lightsalmon) 
  (lightsalmon next-color tomato) 
  (tomato next-color coral) 
  (coral next-color darksalmon) 
  (darksalmon next-color rosybrown) 
  (rosybrown next-color sienna) 
  (sienna next-color saddlebrown) 
  (saddlebrown next-color chocolate) 
  (chocolate next-color peru) 
  (peru next-color sandybrown) 
  (sandybrown next-color burlywood) 
  (burlywood next-color tan) 
  (tan next-color navajowhite) 
  (navajowhite next-color wheat) 
  (wheat next-color darkgoldenrod) 
  (darkgoldenrod next-color goldenrod) 
  (goldenrod next-color lightgoldenrod) 
  (lightgoldenrod next-color palegoldenrod) 
  (palegoldenrod next-color cornsilk) 
  (cornsilk next-color darkkhaki) 
  (darkkhaki next-color khaki) 
  (khaki next-color lemonchiffon) 
  (lemonchiffon next-color darkolivegreen) 
  (darkolivegreen next-color olivedrab) 
  (olivedrab next-color yellowgreen) 
  (yellowgreen next-color greenyellow) 
  (greenyellow next-color lightgreen) 
  (lightgreen next-color forestgreen) 
  (forestgreen next-color darkgreen) 
  (darkgreen next-color limegreen) 
  (limegreen next-color palegreen) 
  (palegreen next-color darkseagreen) 
  (darkseagreen next-color seagreen) 
  (seagreen next-color mediumseagreen) 
  (mediumseagreen next-color lightseagreen) 
  (lightseagreen next-color mediumaquamarine) 
  (mediumaquamarine next-color aquamarine) 
  (aquamarine next-color darkcyan) 
  (darkcyan next-color darkturquoise) 
  (darkturquoise next-color mediumturquoise) 
  (mediumturquoise next-color turquoise) 
  (turquoise next-color paleturquoise) 
  (paleturquoise next-color powderblue) 
  (powderblue next-color lightblue) 
  (lightblue next-color skyblue) 
  (skyblue next-color lightskyblue) 
  (lightskyblue next-color cadetblue) 
  (cadetblue next-color steelblue) 
  (steelblue next-color darkslategrey) 
  (darkslategrey next-color slategrey) 
  (slategrey next-color lightslategrey) 
  (lightslategrey next-color royalblue) 
  (royalblue next-color dodgerblue) 
  (dodgerblue next-color cornflowerblue) 
  (cornflowerblue next-color lightsteelblue) 
  (lightsteelblue next-color darkblue) 
  (darkblue next-color navyblue) 
  (navyblue next-color midnightblue) 
  (midnightblue next-color darkslateblue) 
  (darkslateblue next-color slateblue) 
  (slateblue next-color mediumslateblue) 
  (mediumslateblue next-color lightslateblue) 
  (lightslateblue next-color mediumpurple) 
  (mediumpurple next-color blueviolet) 
  (blueviolet next-color purple) 
  (purple next-color darkorchid) 
  (darkorchid next-color mediumorchid) 
  (mediumorchid next-color orchid) 
  (orchid next-color thistle) 
  (thistle next-color plum) 
  (plum next-color violet) 
  (violet next-color mediumvioletred) 
  (mediumvioletred next-color violetred) 
  (violetred next-color palevioletred) 
  (palevioletred next-color maroon) 
  (maroon next-color deeppink) 
  (deeppink next-color hotpink) 
  (hotpink next-color pink) 
  (pink next-color lightpink) 
  (lightpink next-color snow) 
  (snow next-color mistyrose) 
  (mistyrose next-color seashell) 
  (seashell next-color peachpuff) 
  (peachpuff next-color linen) 
  (linen next-color antiquewhite) 
  (antiquewhite next-color bisque) 
  (bisque next-color papayawhip) 
  (papayawhip next-color moccasin) 
  (moccasin next-color blanchedalmond) 
  (blanchedalmond next-color oldlace) 
  (oldlace next-color floralwhite) 
  (floralwhite next-color beige) 
  (beige next-color lightyellow) 
  (lightyellow next-color lightgoldenrodyellow) 
  (lightgoldenrodyellow next-color ivory) 
  (ivory next-color honeydew) 
  (honeydew next-color mintcream) 
  (mintcream next-color lightcyan) 
  (lightcyan next-color azure) 
  (azure next-color aliceblue) 
  (aliceblue next-color lavender) 
  (lavender next-color ghostwhite) 
  (ghostwhite next-color lavenderblush) 
  (lavenderblush next-color red4) 
  (red4 next-color red3) 
  (red3 next-color red2) 
  (red2 next-color red1) 
  (red1 next-color orangered4) 
  (orangered4 next-color orangered3) 
  (orangered3 next-color orangered2) 
  (orangered2 next-color orangered1) 
  (orangered1 next-color darkorange4) 
  (darkorange4 next-color darkorange3) 
  (darkorange3 next-color darkorange2) 
  (darkorange2 next-color darkorange1) 
  (darkorange1 next-color orange4) 
  (orange4 next-color orange3) 
  (orange3 next-color orange2) 
  (orange2 next-color orange1) 
  (orange1 next-color gold4) 
  (gold4 next-color gold3) 
  (gold3 next-color gold2) 
  (gold2 next-color gold1) 
  (gold1 next-color yellow4) 
  (yellow4 next-color yellow3) 
  (yellow3 next-color yellow2) 
  (yellow2 next-color yellow1) 
  (yellow1 next-color chartreuse4) 
  (chartreuse4 next-color chartreuse3) 
  (chartreuse3 next-color chartreuse2) 
  (chartreuse2 next-color chartreuse1) 
  (chartreuse1 next-color green4) 
  (green4 next-color green3) 
  (green3 next-color green2) 
  (green2 next-color green1) 
  (green1 next-color springgreen4) 
  (springgreen4 next-color springgreen3) 
  (springgreen3 next-color springgreen2) 
  (springgreen2 next-color springgreen1) 
  (springgreen1 next-color cyan4) 
  (cyan4 next-color cyan3) 
  (cyan3 next-color cyan2) 
  (cyan2 next-color cyan1) 
  (cyan1 next-color turquoise4) 
  (turquoise4 next-color turquoise3) 
  (turquoise3 next-color turquoise2) 
  (turquoise2 next-color turquoise1) 
  (turquoise1 next-color deepskyblue4) 
  (deepskyblue4 next-color deepskyblue3) 
  (deepskyblue3 next-color deepskyblue2) 
  (deepskyblue2 next-color deepskyblue1) 
  (deepskyblue1 next-color blue4) 
  (blue4 next-color blue3) 
  (blue3 next-color blue2) 
  (blue2 next-color blue1) 
  (blue1 next-color magenta4) 
  (magenta4 next-color magenta3) 
  (magenta3 next-color magenta2) 
  (magenta2 next-color magenta1) 
  (magenta1 next-color brown4) 
  (brown4 next-color brown3) 
  (brown3 next-color brown2) 
  (brown2 next-color brown1) 
  (brown1 next-color firebrick4) 
  (firebrick4 next-color firebrick3) 
  (firebrick3 next-color firebrick2) 
  (firebrick2 next-color firebrick1) 
  (firebrick1 next-color indianred4) 
  (indianred4 next-color indianred3) 
  (indianred3 next-color indianred2) 
  (indianred2 next-color indianred1) 
  (indianred1 next-color rosybrown4) 
  (rosybrown4 next-color rosybrown3) 
  (rosybrown3 next-color rosybrown2) 
  (rosybrown2 next-color rosybrown1) 
  (rosybrown1 next-color snow4) 
  (snow4 next-color snow3) 
  (snow3 next-color snow2) 
  (snow2 next-color snow1) 
  (snow1 next-color mistyrose4) 
  (mistyrose4 next-color mistyrose3) 
  (mistyrose3 next-color mistyrose2) 
  (mistyrose2 next-color mistyrose1) 
  (mistyrose1 next-color tomato4) 
  (tomato4 next-color tomato3) 
  (tomato3 next-color tomato2) 
  (tomato2 next-color tomato1) 
  (tomato1 next-color coral4) 
  (coral4 next-color coral3) 
  (coral3 next-color coral2) 
  (coral2 next-color coral1) 
  (coral1 next-color salmon4) 
  (salmon4 next-color salmon3) 
  (salmon3 next-color salmon2) 
  (salmon2 next-color salmon1) 
  (salmon1 next-color lightsalmon4) 
  (lightsalmon4 next-color lightsalmon3) 
  (lightsalmon3 next-color lightsalmon2) 
  (lightsalmon2 next-color lightsalmon1) 
  (lightsalmon1 next-color sienna4) 
  (sienna4 next-color sienna3) 
  (sienna3 next-color sienna2) 
  (sienna2 next-color sienna1) 
  (sienna1 next-color chocolate4) 
  (chocolate4 next-color chocolate3) 
  (chocolate3 next-color chocolate2) 
  (chocolate2 next-color chocolate1) 
  (chocolate1 next-color seashell4) 
  (seashell4 next-color seashell3) 
  (seashell3 next-color seashell2) 
  (seashell2 next-color seashell1) 
  (seashell1 next-color peachpuff4) 
  (peachpuff4 next-color peachpuff3) 
  (peachpuff3 next-color peachpuff2) 
  (peachpuff2 next-color peachpuff1) 
  (peachpuff1 next-color tan4) 
  (tan4 next-color tan3) 
  (tan3 next-color tan2) 
  (tan2 next-color tan1) 
  (tan1 next-color bisque4) 
  (bisque4 next-color bisque3) 
  (bisque3 next-color bisque2) 
  (bisque2 next-color bisque1) 
  (bisque1 next-color antiquewhite4) 
  (antiquewhite4 next-color antiquewhite3) 
  (antiquewhite3 next-color antiquewhite2) 
  (antiquewhite2 next-color antiquewhite1) 
  (antiquewhite1 next-color burlywood4) 
  (burlywood4 next-color burlywood3) 
  (burlywood3 next-color burlywood2) 
  (burlywood2 next-color burlywood1) 
  (burlywood1 next-color navajowhite4) 
  (navajowhite4 next-color navajowhite3) 
  (navajowhite3 next-color navajowhite2) 
  (navajowhite2 next-color navajowhite1) 
  (navajowhite1 next-color wheat4) 
  (wheat4 next-color wheat3) 
  (wheat3 next-color wheat2) 
  (wheat2 next-color wheat1) 
  (wheat1 next-color darkgoldenrod4) 
  (darkgoldenrod4 next-color darkgoldenrod3) 
  (darkgoldenrod3 next-color darkgoldenrod2) 
  (darkgoldenrod2 next-color darkgoldenrod1) 
  (darkgoldenrod1 next-color goldenrod4) 
  (goldenrod4 next-color goldenrod3) 
  (goldenrod3 next-color goldenrod2) 
  (goldenrod2 next-color goldenrod1) 
  (goldenrod1 next-color cornsilk4) 
  (cornsilk4 next-color cornsilk3) 
  (cornsilk3 next-color cornsilk2) 
  (cornsilk2 next-color cornsilk1) 
  (cornsilk1 next-color lightgoldenrod4) 
  (lightgoldenrod4 next-color lightgoldenrod3) 
  (lightgoldenrod3 next-color lightgoldenrod2) 
  (lightgoldenrod2 next-color lightgoldenrod1) 
  (lightgoldenrod1 next-color lemonchiffon4) 
  (lemonchiffon4 next-color lemonchiffon3) 
  (lemonchiffon3 next-color lemonchiffon2) 
  (lemonchiffon2 next-color lemonchiffon1) 
  (lemonchiffon1 next-color khaki4) 
  (khaki4 next-color khaki3) 
  (khaki3 next-color khaki2) 
  (khaki2 next-color khaki1) 
  (khaki1 next-color lightyellow4) 
  (lightyellow4 next-color lightyellow3) 
  (lightyellow3 next-color lightyellow2) 
  (lightyellow2 next-color lightyellow1) 
  (lightyellow1 next-color ivory4) 
  (ivory4 next-color ivory3) 
  (ivory3 next-color ivory2) 
  (ivory2 next-color ivory1) 
  (ivory1 next-color olivedrab4) 
  (olivedrab4 next-color olivedrab3) 
  (olivedrab3 next-color olivedrab2) 
  (olivedrab2 next-color olivedrab1) 
  (olivedrab1 next-color darkolivegreen4) 
  (darkolivegreen4 next-color darkolivegreen3) 
  (darkolivegreen3 next-color darkolivegreen2) 
  (darkolivegreen2 next-color darkolivegreen1) 
  (darkolivegreen1 next-color palegreen4) 
  (palegreen4 next-color palegreen3) 
  (palegreen3 next-color palegreen2) 
  (palegreen2 next-color palegreen1) 
  (palegreen1 next-color darkseagreen4) 
  (darkseagreen4 next-color darkseagreen3) 
  (darkseagreen3 next-color darkseagreen2) 
  (darkseagreen2 next-color darkseagreen1) 
  (darkseagreen1 next-color honeydew4) 
  (honeydew4 next-color honeydew3) 
  (honeydew3 next-color honeydew2) 
  (honeydew2 next-color honeydew1) 
  (honeydew1 next-color seagreen4) 
  (seagreen4 next-color seagreen3) 
  (seagreen3 next-color seagreen2) 
  (seagreen2 next-color seagreen1) 
  (seagreen1 next-color aquamarine4) 
  (aquamarine4 next-color aquamarine3) 
  (aquamarine3 next-color aquamarine2) 
  (aquamarine2 next-color aquamarine1) 
  (aquamarine1 next-color darkslategray4) 
  (darkslategray4 next-color darkslategray3) 
  (darkslategray3 next-color darkslategray2) 
  (darkslategray2 next-color darkslategray1) 
  (darkslategray1 next-color paleturquoise4) 
  (paleturquoise4 next-color paleturquoise3) 
  (paleturquoise3 next-color paleturquoise2) 
  (paleturquoise2 next-color paleturquoise1) 
  (paleturquoise1 next-color lightcyan4) 
  (lightcyan4 next-color lightcyan3) 
  (lightcyan3 next-color lightcyan2) 
  (lightcyan2 next-color lightcyan1) 
  (lightcyan1 next-color azure4) 
  (azure4 next-color azure3) 
  (azure3 next-color azure2) 
  (azure2 next-color azure1) 
  (azure1 next-color cadetblue4) 
  (cadetblue4 next-color cadetblue3) 
  (cadetblue3 next-color cadetblue2) 
  (cadetblue2 next-color cadetblue1) 
  (cadetblue1 next-color lightblue4) 
  (lightblue4 next-color lightblue3) 
  (lightblue3 next-color lightblue2) 
  (lightblue2 next-color lightblue1) 
  (lightblue1 next-color lightskyblue4) 
  (lightskyblue4 next-color lightskyblue3) 
  (lightskyblue3 next-color lightskyblue2) 
  (lightskyblue2 next-color lightskyblue1) 
  (lightskyblue1 next-color skyblue4) 
  (skyblue4 next-color skyblue3) 
  (skyblue3 next-color skyblue2) 
  (skyblue2 next-color skyblue1) 
  (skyblue1 next-color steelblue4) 
  (steelblue4 next-color steelblue3) 
  (steelblue3 next-color steelblue2) 
  (steelblue2 next-color steelblue1) 
  (steelblue1 next-color dodgerblue4) 
  (dodgerblue4 next-color dodgerblue3) 
  (dodgerblue3 next-color dodgerblue2) 
  (dodgerblue2 next-color dodgerblue1) 
  (dodgerblue1 next-color slategray4) 
  (slategray4 next-color slategray3) 
  (slategray3 next-color slategray2) 
  (slategray2 next-color slategray1) 
  (slategray1 next-color lightsteelblue4) 
  (lightsteelblue4 next-color lightsteelblue3) 
  (lightsteelblue3 next-color lightsteelblue2) 
  (lightsteelblue2 next-color lightsteelblue1) 
  (lightsteelblue1 next-color royalblue4) 
  (royalblue4 next-color royalblue3) 
  (royalblue3 next-color royalblue2) 
  (royalblue2 next-color royalblue1) 
  (royalblue1 next-color slateblue4) 
  (slateblue4 next-color slateblue3) 
  (slateblue3 next-color slateblue2) 
  (slateblue2 next-color slateblue1) 
  (slateblue1 next-color mediumpurple4) 
  (mediumpurple4 next-color mediumpurple3) 
  (mediumpurple3 next-color mediumpurple2) 
  (mediumpurple2 next-color mediumpurple1) 
  (mediumpurple1 next-color purple4) 
  (purple4 next-color purple3) 
  (purple3 next-color purple2) 
  (purple2 next-color purple1) 
  (purple1 next-color darkorchid4) 
  (darkorchid4 next-color darkorchid3) 
  (darkorchid3 next-color darkorchid2) 
  (darkorchid2 next-color darkorchid1) 
  (darkorchid1 next-color mediumorchid4) 
  (mediumorchid4 next-color mediumorchid3) 
  (mediumorchid3 next-color mediumorchid2) 
  (mediumorchid2 next-color mediumorchid1) 
  (mediumorchid1 next-color thistle4) 
  (thistle4 next-color thistle3) 
  (thistle3 next-color thistle2) 
  (thistle2 next-color thistle1) 
  (thistle1 next-color plum4) 
  (plum4 next-color plum3) 
  (plum3 next-color plum2) 
  (plum2 next-color plum1) 
  (plum1 next-color orchid4) 
  (orchid4 next-color orchid3) 
  (orchid3 next-color orchid2) 
  (orchid2 next-color orchid1) 
  (orchid1 next-color maroon4) 
  (maroon4 next-color maroon3) 
  (maroon3 next-color maroon2) 
  (maroon2 next-color maroon1) 
  (maroon1 next-color deeppink4) 
  (deeppink4 next-color deeppink3) 
  (deeppink3 next-color deeppink2) 
  (deeppink2 next-color deeppink1) 
  (deeppink1 next-color hotpink4) 
  (hotpink4 next-color hotpink3) 
  (hotpink3 next-color hotpink2) 
  (hotpink2 next-color hotpink1) 
  (hotpink1 next-color violetred4) 
  (violetred4 next-color violetred3) 
  (violetred3 next-color violetred2) 
  (violetred2 next-color violetred1) 
  (violetred1 next-color lavenderblush4) 
  (lavenderblush4 next-color lavenderblush3) 
  (lavenderblush3 next-color lavenderblush2) 
  (lavenderblush2 next-color lavenderblush1) 
  (lavenderblush1 next-color palevioletred4) 
  (palevioletred4 next-color palevioletred3) 
  (palevioletred3 next-color palevioletred2) 
  (palevioletred2 next-color palevioletred1) 
  (palevioletred1 next-color pink4) 
  (pink4 next-color pink3) 
  (pink3 next-color pink2) 
  (pink2 next-color pink1) 
  (pink1 next-color lightpink4) 
  (lightpink4 next-color lightpink3) 
  (lightpink3 next-color lightpink2) 
  (lightpink2 next-color lightpink1)
  (lightpink1 next-color red))
 (del
  (global-node rule ?this-rule)))
)

(rule
 (name color-color)
 (attach-to global-node)
 (root-var global-node)
 (pred
  (global-node next-color)
  (?x next-color ?y))
 (add
  (print color-color ?x)
  (?x color ?x))
 (del
  (?this-obj rule ?this-rule)))



